---
- name: Deploy EC2 instance
  import_playbook: ./modules/create_ec2.yml
  vars:
    host_group_name: "{{ host }}"
    ec2_name: "JCE-Artifactory-{{ artifactory_version }}"

- name: Allow time for EC2 to spin up
  hosts: localhost
  connection: local
  tasks: 
    - name: Wait for 5 minutes
      wait_for:
        timeout: 300

- name: Install Docker
  import_playbook: ./modules/install_docker.yml
  vars:
    host: "{{ host }}"
    username: "{{ username }}"
    pem_key: "{{ pem_key }}"

- name: Deploy Artifactory on EC2 instance
  hosts: "{{ host }}"
  remote_user: "{{ username }}"
  vars:
    ansible_ssh_private_key_file: "{{ pem_key }}"
    create_ec2: disabled
    artifactory_version: oss

  tasks:

  - name: Run Artifactory Docker image
    shell: > 
      docker run --name JCE-Artifactory-"{{ artifactory_version }}" -d -p 8081:8081 -p 8082:8082 
      docker.bintray.io/jfrog/artifactory-"{{ artifactory_version }}":latest
